"""Default bot texts (EN / RU / ZH).

Every customer-facing string of the bot has a key here. Administrators can override
any key for any language from the dashboard (Bot Editor); overrides are stored in the
`translations` table. Texts use Telegram HTML and `{placeholders}`.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class TextDef:
    key: str
    section: str
    en: str
    ru: str
    zh: str
    description: str = ""
    variables: tuple[str, ...] = field(default_factory=tuple)

    def get(self, lang: str) -> str | None:
        return getattr(self, lang, None) if lang in ("en", "ru", "zh") else None


T = TextDef

TEXTS: list[TextDef] = [
    # ── Common buttons ──────────────────────────────────────────────────────
    T("btn.back", "Buttons", "← Back", "← Назад", "← 返回"),
    T("btn.home", "Buttons", "🏠 Home", "🏠 Главная", "🏠 首页"),
    T("btn.cancel", "Buttons", "✕ Cancel", "✕ Отмена", "✕ 取消"),
    T("btn.confirm", "Buttons", "✓ Confirm", "✓ Подтвердить", "✓ 确认"),
    T("btn.yes", "Buttons", "Yes", "Да", "是"),
    T("btn.no", "Buttons", "No", "Нет", "否"),
    T("btn.prev", "Buttons", "‹", "‹", "‹"),
    T("btn.next", "Buttons", "›", "›", "›"),
    T("btn.catalog", "Buttons", "🛍 Catalog", "🛍 Каталог", "🛍 商品目录"),
    T("btn.cart", "Buttons", "🛒 Cart", "🛒 Корзина", "🛒 购物车"),
    T("btn.cart_count", "Buttons", "🛒 Cart · {count}", "🛒 Корзина · {count}", "🛒 购物车 · {count}", variables=("count",)),
    T("btn.orders", "Buttons", "📦 My orders", "📦 Мои заказы", "📦 我的订单"),
    T("btn.profile", "Buttons", "👤 Profile", "👤 Профиль", "👤 个人中心"),
    T("btn.support", "Buttons", "💬 Support", "💬 Поддержка", "💬 客服支持"),
    T("btn.faq", "Buttons", "❓ FAQ", "❓ FAQ", "❓ 常见问题"),
    T("btn.search", "Buttons", "🔎 Search", "🔎 Поиск", "🔎 搜索"),
    T("btn.favorites", "Buttons", "♥ Favorites", "♥ Избранное", "♥ 收藏"),
    T("btn.recent", "Buttons", "🕘 Recently viewed", "🕘 Недавно смотрели", "🕘 最近浏览"),
    T("btn.referrals", "Buttons", "🎁 Invite friends", "🎁 Пригласить друзей", "🎁 邀请好友"),
    T("btn.language", "Buttons", "🌐 Language", "🌐 Язык", "🌐 语言"),
    T("btn.terms", "Buttons", "📄 Terms", "📄 Условия", "📄 条款"),
    T("btn.add_to_cart", "Buttons", "🛒 Add to cart", "🛒 В корзину", "🛒 加入购物车"),
    T("btn.buy_now", "Buttons", "⚡ Buy now", "⚡ Купить сейчас", "⚡ 立即购买"),
    T("btn.favorite_add", "Buttons", "♡ Save", "♡ В избранное", "♡ 收藏"),
    T("btn.favorite_remove", "Buttons", "♥ Saved", "♥ В избранном", "♥ 已收藏"),
    T("btn.notify_restock", "Buttons", "🔔 Notify me", "🔔 Сообщить о поступлении", "🔔 到货提醒"),
    T("btn.restock_subscribed", "Buttons", "🔕 Subscribed", "🔕 Подписка оформлена", "🔕 已订阅"),
    T("btn.reviews", "Buttons", "⭐ Reviews ({count})", "⭐ Отзывы ({count})", "⭐ 评价 ({count})", variables=("count",)),
    T("btn.checkout", "Buttons", "💳 Checkout · {total}", "💳 Оформить · {total}", "💳 结算 · {total}", variables=("total",)),
    T("btn.clear_cart", "Buttons", "🗑 Clear", "🗑 Очистить", "🗑 清空"),
    T("btn.promo", "Buttons", "🏷 Promo code", "🏷 Промокод", "🏷 优惠码"),
    T("btn.remove_promo", "Buttons", "✕ Remove promo", "✕ Убрать промокод", "✕ 移除优惠码"),
    T("btn.use_balance", "Buttons", "💰 Use balance ({balance})", "💰 Списать баланс ({balance})", "💰 使用余额 ({balance})", variables=("balance",)),
    T("btn.balance_used", "Buttons", "✅ Balance applied", "✅ Баланс применён", "✅ 已使用余额"),
    T("btn.pay_open", "Buttons", "💳 Pay {amount}", "💳 Оплатить {amount}", "💳 支付 {amount}", variables=("amount",)),
    T("btn.check_payment", "Buttons", "🔄 Check payment", "🔄 Проверить оплату", "🔄 检查付款"),
    T("btn.i_paid", "Buttons", "✅ I have paid", "✅ Я оплатил", "✅ 我已付款"),
    T("btn.cancel_order", "Buttons", "✕ Cancel order", "✕ Отменить заказ", "✕ 取消订单"),
    T("btn.change_method", "Buttons", "↺ Other method", "↺ Другой способ", "↺ 其他方式"),
    T("btn.show_qr", "Buttons", "▦ QR code", "▦ QR-код", "▦ 二维码"),
    T("btn.copy_address", "Buttons", "⧉ Copy address", "⧉ Скопировать адрес", "⧉ 复制地址"),
    T("btn.copy_amount", "Buttons", "⧉ Copy amount", "⧉ Скопировать сумму", "⧉ 复制金额"),
    T("btn.order_support", "Buttons", "💬 Help with this order", "💬 Помощь по заказу", "💬 订单帮助"),
    T("btn.leave_review", "Buttons", "⭐ Leave a review", "⭐ Оставить отзыв", "⭐ 留下评价"),
    T("btn.view_order", "Buttons", "📦 View order", "📦 Открыть заказ", "📦 查看订单"),
    T("btn.new_ticket", "Buttons", "✉️ New request", "✉️ Новое обращение", "✉️ 新建工单"),
    T("btn.my_tickets", "Buttons", "🗂 My requests", "🗂 Мои обращения", "🗂 我的工单"),
    T("btn.reply", "Buttons", "↩ Reply", "↩ Ответить", "↩ 回复"),
    T("btn.close_ticket", "Buttons", "✓ Close request", "✓ Закрыть обращение", "✓ 关闭工单"),
    T("btn.contact_manager", "Buttons", "👤 Contact a manager", "👤 Написать менеджеру", "👤 联系客服"),
    T("btn.check_subscription", "Buttons", "✓ I've subscribed", "✓ Я подписался", "✓ 我已订阅"),
    T("btn.share_referral", "Buttons", "📤 Share link", "📤 Поделиться ссылкой", "📤 分享链接"),
    T("btn.reorder", "Buttons", "↻ Buy again", "↻ Купить снова", "↻ 再次购买"),

    # ── Common states ───────────────────────────────────────────────────────
    T("common.footer", "Common", "", "", "", "Footer appended to the main screens (leave empty to hide)"),
    T("common.loading", "Common", "⏳ One moment…", "⏳ Секунду…", "⏳ 请稍候…"),
    T("common.page", "Common", "Page {page}/{pages}", "Стр. {page}/{pages}", "第 {page}/{pages} 页", variables=("page", "pages")),
    T("error.generic", "Errors", "⚠️ Something went wrong. Please try again in a moment.",
      "⚠️ Что-то пошло не так. Попробуйте ещё раз чуть позже.", "⚠️ 出了点问题，请稍后重试。"),
    T("error.not_found", "Errors", "This item is no longer available.", "Этот раздел больше недоступен.", "该内容已不可用。"),
    T("error.rate_limit", "Errors", "Easy there — too many requests. Try again in a few seconds.",
      "Слишком много запросов. Попробуйте через пару секунд.", "操作过于频繁，请几秒后再试。"),
    T("error.banned", "Errors", "🚫 Your access to this store has been restricted.\n\nIf you think this is a mistake, contact support.",
      "🚫 Доступ к магазину ограничен.\n\nЕсли это ошибка — напишите в поддержку.", "🚫 您的访问已被限制。\n\n如有疑问，请联系客服。"),
    T("error.session_expired", "Errors", "This screen has expired. Opening a fresh one…",
      "Этот экран устарел. Открываю заново…", "该页面已过期，正在重新打开…"),
    T("error.feature_disabled", "Errors", "This feature is currently unavailable.", "Эта функция сейчас недоступна.", "该功能暂不可用。"),
    T("maintenance.text", "Common",
      "🛠 <b>We'll be right back</b>\n\nThe store is undergoing scheduled maintenance. Please check back shortly.",
      "🛠 <b>Скоро вернёмся</b>\n\nВ магазине проходят технические работы. Загляните немного позже.",
      "🛠 <b>马上回来</b>\n\n商店正在维护中，请稍后再来。"),
    T("subscription.required", "Common",
      "📣 <b>One more step</b>\n\nSubscribe to our channel to access the store:\n{channels}",
      "📣 <b>Ещё один шаг</b>\n\nПодпишитесь на наш канал, чтобы пользоваться магазином:\n{channels}",
      "📣 <b>还差一步</b>\n\n请订阅我们的频道以访问商店：\n{channels}", variables=("channels",)),
    T("subscription.not_yet", "Common", "We couldn't find your subscription yet.", "Подписка пока не найдена.", "尚未检测到您的订阅。"),

    # ── Home ────────────────────────────────────────────────────────────────
    T("home.text", "Home",
      "<b>Welcome to {store_name}</b>, {first_name} ✨\n\nPremium digital products with instant delivery — 24/7, fully automated.\n\n<blockquote>⚡ Instant delivery · 🛡 Warranty · 💬 Live support</blockquote>",
      "<b>Добро пожаловать в {store_name}</b>, {first_name} ✨\n\nПремиальные цифровые товары с мгновенной выдачей — 24/7, полностью автоматически.\n\n<blockquote>⚡ Мгновенная выдача · 🛡 Гарантия · 💬 Поддержка</blockquote>",
      "<b>欢迎来到 {store_name}</b>，{first_name} ✨\n\n优质数字商品，全天候自动即时发货。\n\n<blockquote>⚡ 即时发货 · 🛡 售后保障 · 💬 在线客服</blockquote>",
      "Main welcome screen", ("store_name", "first_name", "balance", "orders_count")),
    T("home.returning", "Home",
      "<b>Welcome back, {first_name}</b> 👋\n\nWhat are we getting today?",
      "<b>С возвращением, {first_name}</b> 👋\n\nЧто подберём сегодня?",
      "<b>欢迎回来，{first_name}</b> 👋\n\n今天想买点什么？",
      "Shown to returning customers with at least one order", ("first_name", "store_name")),
    T("announcement.title", "Home", "📢 <b>Announcement</b>", "📢 <b>Объявление</b>", "📢 <b>公告</b>"),

    # ── Catalog ─────────────────────────────────────────────────────────────
    T("catalog.title", "Catalog", "🛍 <b>Catalog</b>\n\nChoose a category:", "🛍 <b>Каталог</b>\n\nВыберите категорию:", "🛍 <b>商品目录</b>\n\n请选择分类："),
    T("catalog.empty", "Catalog", "The catalog is being prepared — check back soon.", "Каталог скоро наполнится — загляните позже.", "商品即将上架，敬请期待。"),
    T("category.text", "Catalog", "{emoji} <b>{name}</b>\n\n{description}", "{emoji} <b>{name}</b>\n\n{description}", "{emoji} <b>{name}</b>\n\n{description}",
      "Category screen", ("emoji", "name", "description", "count")),
    T("category.empty", "Catalog", "No products in this category yet.", "В этой категории пока нет товаров.", "该分类暂无商品。"),
    T("product.card", "Product",
      "{emoji} <b>{name}</b>\n{short_description}\n\n{price_block}\n{stock}{rating}\n\n{description}{warranty}",
      "{emoji} <b>{name}</b>\n{short_description}\n\n{price_block}\n{stock}{rating}\n\n{description}{warranty}",
      "{emoji} <b>{name}</b>\n{short_description}\n\n{price_block}\n{stock}{rating}\n\n{description}{warranty}",
      "Product page template", ("emoji", "name", "short_description", "description", "price_block", "stock", "rating", "warranty", "variant")),
    T("product.price", "Product", "💰 <b>{price}</b>", "💰 <b>{price}</b>", "💰 <b>{price}</b>", variables=("price",)),
    T("product.price_from", "Product", "💰 from <b>{price}</b>", "💰 от <b>{price}</b>", "💰 <b>{price}</b> 起", variables=("price",)),
    T("product.price_discount", "Product", "💰 <b>{price}</b>  <s>{old_price}</s>  <i>−{percent}%</i>",
      "💰 <b>{price}</b>  <s>{old_price}</s>  <i>−{percent}%</i>", "💰 <b>{price}</b>  <s>{old_price}</s>  <i>−{percent}%</i>",
      variables=("price", "old_price", "percent")),
    T("product.in_stock", "Product", "🟢 In stock", "🟢 В наличии", "🟢 有货"),
    T("product.in_stock_count", "Product", "🟢 In stock: {count}", "🟢 В наличии: {count}", "🟢 库存：{count}", variables=("count",)),
    T("product.low_stock", "Product", "🟠 Only {count} left", "🟠 Осталось {count}", "🟠 仅剩 {count} 件", variables=("count",)),
    T("product.out_of_stock", "Product", "🔴 Out of stock", "🔴 Нет в наличии", "🔴 暂时缺货"),
    T("product.rating", "Product", " · ⭐ {rating} ({count})", " · ⭐ {rating} ({count})", " · ⭐ {rating} ({count})", variables=("rating", "count")),
    T("product.warranty", "Product", "\n\n🛡 <b>Warranty:</b> {warranty}", "\n\n🛡 <b>Гарантия:</b> {warranty}", "\n\n🛡 <b>保修：</b>{warranty}", variables=("warranty",)),
    T("product.choose_option", "Product", "\n\n<b>Choose {option}:</b>", "\n\n<b>Выберите {option}:</b>", "\n\n<b>请选择{option}：</b>", variables=("option",)),
    T("product.selected", "Product", "\n\n✔ <b>{variant}</b>", "\n\n✔ <b>{variant}</b>", "\n\n✔ <b>{variant}</b>", variables=("variant",)),
    T("product.quantity", "Product", "Quantity: <b>{qty}</b>", "Количество: <b>{qty}</b>", "数量：<b>{qty}</b>", variables=("qty",)),
    T("product.added", "Product", "✓ Added to cart", "✓ Добавлено в корзину", "✓ 已加入购物车"),
    T("product.limit_reached", "Product", "Purchase limit for this product reached", "Достигнут лимит покупки товара", "已达到该商品购买上限"),
    T("product.favorite_added", "Product", "♥ Saved to favorites", "♥ Добавлено в избранное", "♥ 已收藏"),
    T("product.favorite_removed", "Product", "Removed from favorites", "Удалено из избранного", "已取消收藏"),
    T("product.restock_subscribed", "Product", "🔔 We'll message you when it's back", "🔔 Сообщим, когда товар появится", "🔔 到货后我们会通知您"),
    T("product.reviews_title", "Product", "⭐ <b>Reviews · {name}</b>\n\nAverage {rating} from {count} reviews\n\n{reviews}",
      "⭐ <b>Отзывы · {name}</b>\n\nСредняя оценка {rating} из {count} отзывов\n\n{reviews}",
      "⭐ <b>评价 · {name}</b>\n\n平均 {rating}，共 {count} 条评价\n\n{reviews}", variables=("name", "rating", "count", "reviews")),
    T("product.no_reviews", "Product", "No reviews yet — be the first after your purchase.", "Отзывов пока нет.", "暂无评价。"),

    # ── Search / favorites / recent ─────────────────────────────────────────
    T("search.prompt", "Search", "🔎 <b>Search</b>\n\nSend me what you're looking for — a product name, brand or keyword.",
      "🔎 <b>Поиск</b>\n\nНапишите, что ищете — название, бренд или ключевое слово.", "🔎 <b>搜索</b>\n\n请发送商品名称、品牌或关键词。"),
    T("search.results", "Search", "🔎 Results for “<b>{query}</b>”:", "🔎 Результаты по запросу «<b>{query}</b>»:", "🔎 “<b>{query}</b>” 的搜索结果：", variables=("query",)),
    T("search.empty", "Search", "Nothing found for “<b>{query}</b>”. Try another keyword.", "По запросу «<b>{query}</b>» ничего не найдено.", "未找到 “<b>{query}</b>” 相关商品。", variables=("query",)),
    T("favorites.title", "Favorites", "♥ <b>Favorites</b>", "♥ <b>Избранное</b>", "♥ <b>我的收藏</b>"),
    T("favorites.empty", "Favorites", "♡ <b>No favorites yet</b>\n\nTap ♡ on any product to save it here.", "♡ <b>Избранное пусто</b>\n\nНажмите ♡ на товаре, чтобы сохранить его.", "♡ <b>暂无收藏</b>\n\n在商品页点击 ♡ 即可收藏。"),
    T("recent.title", "Favorites", "🕘 <b>Recently viewed</b>", "🕘 <b>Недавно просмотренные</b>", "🕘 <b>最近浏览</b>"),
    T("recent.empty", "Favorites", "You haven't viewed any products yet.", "Вы ещё не смотрели товары.", "您还没有浏览过商品。"),
    T("recommend.title", "Product", "✨ <b>You may also like</b>", "✨ <b>Вам может понравиться</b>", "✨ <b>猜你喜欢</b>"),

    # ── Cart ────────────────────────────────────────────────────────────────
    T("cart.title", "Cart", "🛒 <b>Your cart</b>\n\n{items}\n\n{summary}", "🛒 <b>Ваша корзина</b>\n\n{items}\n\n{summary}", "🛒 <b>购物车</b>\n\n{items}\n\n{summary}", variables=("items", "summary")),
    T("cart.item", "Cart", "{index}. {emoji} <b>{name}</b>{variant}\n     {qty} × {price} = <b>{total}</b>", "{index}. {emoji} <b>{name}</b>{variant}\n     {qty} × {price} = <b>{total}</b>",
      "{index}. {emoji} <b>{name}</b>{variant}\n     {qty} × {price} = <b>{total}</b>", variables=("index", "emoji", "name", "variant", "qty", "price", "total")),
    T("cart.subtotal", "Cart", "Subtotal: {amount}", "Подытог: {amount}", "小计：{amount}", variables=("amount",)),
    T("cart.discount", "Cart", "Discount ({code}): −{amount}", "Скидка ({code}): −{amount}", "优惠 ({code})：−{amount}", variables=("code", "amount")),
    T("cart.balance", "Cart", "Balance: −{amount}", "С баланса: −{amount}", "余额抵扣：−{amount}", variables=("amount",)),
    T("cart.total", "Cart", "<b>Total: {amount}</b>", "<b>Итого: {amount}</b>", "<b>合计：{amount}</b>", variables=("amount",)),
    T("cart.empty", "Cart", "🛒 <b>Your cart is empty</b>\n\nBrowse the catalog and add something you like.", "🛒 <b>Корзина пуста</b>\n\nЗагляните в каталог и добавьте что-нибудь.", "🛒 <b>购物车是空的</b>\n\n去商品目录看看吧。"),
    T("cart.clear_confirm", "Cart", "Remove all items from the cart?", "Удалить все товары из корзины?", "确定清空购物车？"),
    T("cart.cleared", "Cart", "Cart cleared", "Корзина очищена", "购物车已清空"),
    T("cart.item_unavailable", "Cart", "⚠️ Some items are no longer available and were removed.", "⚠️ Некоторые товары больше недоступны и были удалены.", "⚠️ 部分商品已下架并被移除。"),
    T("cart.promo_prompt", "Cart", "🏷 <b>Promo code</b>\n\nSend your promo code as a message.", "🏷 <b>Промокод</b>\n\nОтправьте промокод сообщением.", "🏷 <b>优惠码</b>\n\n请直接发送优惠码。"),
    T("cart.promo_applied", "Cart", "🏷 Promo code <b>{code}</b> applied — you save {amount}", "🏷 Промокод <b>{code}</b> применён — экономия {amount}", "🏷 已使用优惠码 <b>{code}</b>，节省 {amount}", variables=("code", "amount")),
    T("cart.promo_invalid", "Cart", "⚠️ {reason}", "⚠️ {reason}", "⚠️ {reason}", variables=("reason",)),

    # ── Promo errors ────────────────────────────────────────────────────────
    T("promo.not_found", "Promo", "This promo code doesn't exist.", "Такого промокода не существует.", "该优惠码不存在。"),
    T("promo.disabled", "Promo", "This promo code is no longer active.", "Промокод больше не действует.", "该优惠码已失效。"),
    T("promo.not_started", "Promo", "This promo code isn't active yet.", "Промокод ещё не активен.", "该优惠码尚未生效。"),
    T("promo.expired", "Promo", "This promo code has expired.", "Срок действия промокода истёк.", "该优惠码已过期。"),
    T("promo.exhausted", "Promo", "This promo code has reached its usage limit.", "Лимит использования промокода исчерпан.", "该优惠码已达使用上限。"),
    T("promo.user_limit", "Promo", "You've already used this promo code.", "Вы уже использовали этот промокод.", "您已使用过该优惠码。"),
    T("promo.min_purchase", "Promo", "Minimum order for this code is {amount}.", "Минимальная сумма заказа для промокода — {amount}.", "使用该优惠码的最低消费为 {amount}。", variables=("amount",)),
    T("promo.not_applicable", "Promo", "This promo code doesn't apply to the items in your cart.", "Промокод не распространяется на товары в корзине.", "该优惠码不适用于购物车中的商品。"),
    T("promo.new_only", "Promo", "This promo code is for new customers only.", "Промокод только для новых покупателей.", "该优惠码仅限新用户使用。"),
    T("promo.not_allowed", "Promo", "This promo code isn't available for your account.", "Промокод недоступен для вашего аккаунта.", "您的账户无法使用该优惠码。"),

    # ── Checkout & payment ──────────────────────────────────────────────────
    T("checkout.choose_method", "Checkout", "💳 <b>Checkout · Order {order}</b>\n\n{items}\n\n{summary}\n\nChoose a payment method:",
      "💳 <b>Оформление · Заказ {order}</b>\n\n{items}\n\n{summary}\n\nВыберите способ оплаты:", "💳 <b>结算 · 订单 {order}</b>\n\n{items}\n\n{summary}\n\n请选择支付方式：", variables=("order", "items", "summary")),
    T("checkout.no_methods", "Checkout", "No payment methods are available right now. Please contact support.", "Сейчас нет доступных способов оплаты. Напишите в поддержку.", "暂无可用的支付方式，请联系客服。"),
    T("checkout.min_amount", "Checkout", "Minimum order amount is {amount}.", "Минимальная сумма заказа — {amount}.", "最低订单金额为 {amount}。", variables=("amount",)),
    T("checkout.max_amount", "Checkout", "Maximum order amount is {amount}.", "Максимальная сумма заказа — {amount}.", "最高订单金额为 {amount}。", variables=("amount",)),
    T("checkout.out_of_stock", "Checkout", "⚠️ Not enough stock for <b>{name}</b>. Please adjust your cart.", "⚠️ Недостаточно товара <b>{name}</b>. Измените корзину.", "⚠️ <b>{name}</b> 库存不足，请调整购物车。", variables=("name",)),
    T("checkout.paid_by_balance", "Checkout", "✅ Paid from your balance.", "✅ Оплачено с баланса.", "✅ 已使用余额支付。"),
    T("payment.crypto", "Payment",
      "💎 <b>Payment · Order {order}</b>\n\nSend <b>exactly</b> the amount below to the address:\n\n<b>Network:</b> {network}\n<b>Amount:</b> <code>{amount}</code> {currency}\n<b>Address:</b>\n<code>{address}</code>{memo}\n\n⏱ Expires in <b>{expires}</b>\n\n<blockquote>The payment is detected automatically after {confirmations} network confirmation(s). Send the exact amount in a single transaction — otherwise it can't be matched.</blockquote>",
      "💎 <b>Оплата · Заказ {order}</b>\n\nОтправьте <b>ровно</b> указанную сумму на адрес:\n\n<b>Сеть:</b> {network}\n<b>Сумма:</b> <code>{amount}</code> {currency}\n<b>Адрес:</b>\n<code>{address}</code>{memo}\n\n⏱ Действует ещё <b>{expires}</b>\n\n<blockquote>Платёж определится автоматически после {confirmations} подтверждения(-й) сети. Отправьте точную сумму одной транзакцией — иначе платёж не будет сопоставлен.</blockquote>",
      "💎 <b>付款 · 订单 {order}</b>\n\n请向以下地址转账<b>精确</b>金额：\n\n<b>网络：</b>{network}\n<b>金额：</b><code>{amount}</code> {currency}\n<b>地址：</b>\n<code>{address}</code>{memo}\n\n⏱ 剩余时间 <b>{expires}</b>\n\n<blockquote>网络确认 {confirmations} 次后将自动识别付款。请一次性转入精确金额，否则无法匹配。</blockquote>",
      variables=("order", "network", "amount", "currency", "address", "memo", "expires", "confirmations")),
    T("payment.memo", "Payment", "\n<b>Comment / memo (required):</b> <code>{memo}</code>", "\n<b>Комментарий / memo (обязательно):</b> <code>{memo}</code>", "\n<b>备注 / memo（必填）：</b><code>{memo}</code>", variables=("memo",)),
    T("payment.invoice", "Payment",
      "💳 <b>Payment · Order {order}</b>\n\nAmount: <b>{amount}</b>\nMethod: {method}\n\nTap the button below to pay. The order is confirmed automatically.\n\n⏱ Expires in <b>{expires}</b>",
      "💳 <b>Оплата · Заказ {order}</b>\n\nСумма: <b>{amount}</b>\nСпособ: {method}\n\nНажмите кнопку ниже для оплаты. Заказ подтвердится автоматически.\n\n⏱ Действует ещё <b>{expires}</b>",
      "💳 <b>付款 · 订单 {order}</b>\n\n金额：<b>{amount}</b>\n方式：{method}\n\n点击下方按钮付款，订单将自动确认。\n\n⏱ 剩余时间 <b>{expires}</b>", variables=("order", "amount", "method", "expires")),
    T("payment.manual", "Payment",
      "🏦 <b>Payment · Order {order}</b>\n\nAmount: <b>{amount}</b>\n\n{instructions}\n\nAfter paying, tap <b>“I have paid”</b>. A manager will verify and confirm your order.",
      "🏦 <b>Оплата · Заказ {order}</b>\n\nСумма: <b>{amount}</b>\n\n{instructions}\n\nПосле оплаты нажмите <b>«Я оплатил»</b>. Менеджер проверит и подтвердит заказ.",
      "🏦 <b>付款 · 订单 {order}</b>\n\n金额：<b>{amount}</b>\n\n{instructions}\n\n付款后请点击<b>“我已付款”</b>，客服核实后将确认订单。", variables=("order", "amount", "instructions")),
    T("payment.stars", "Payment", "⭐ <b>Payment · Order {order}</b>\n\nPay <b>{stars} Stars</b> with Telegram — fast and secure.",
      "⭐ <b>Оплата · Заказ {order}</b>\n\nОплатите <b>{stars} Stars</b> через Telegram — быстро и безопасно.", "⭐ <b>付款 · 订单 {order}</b>\n\n使用 Telegram 支付 <b>{stars} Stars</b>，快速安全。", variables=("order", "stars")),
    T("payment.invoice_title", "Payment", "Order {order}", "Заказ {order}", "订单 {order}", variables=("order",)),
    T("payment.invoice_description", "Payment", "{items}", "{items}", "{items}", variables=("items",)),
    T("payment.waiting_manual", "Payment", "⏳ <b>Thanks!</b> Your payment for order {order} is being verified. We'll notify you as soon as it's confirmed.",
      "⏳ <b>Спасибо!</b> Оплата заказа {order} проверяется. Мы сообщим, как только она подтвердится.", "⏳ <b>谢谢！</b>订单 {order} 的付款正在核实中，确认后会立即通知您。", variables=("order",)),
    T("payment.not_found_yet", "Payment", "Payment not detected yet. It can take a few minutes after sending.", "Платёж пока не найден. После отправки это может занять несколько минут.", "暂未检测到付款，转账后可能需要几分钟。"),
    T("payment.detected", "Payment", "🔎 Payment detected — waiting for confirmations ({confirmations}/{required})", "🔎 Платёж найден — ждём подтверждений ({confirmations}/{required})", "🔎 已检测到付款 — 等待确认 ({confirmations}/{required})", variables=("confirmations", "required")),
    T("payment.expired", "Payment", "⌛ <b>Payment window expired</b>\n\nOrder {order} was cancelled because payment wasn't received in time. If you already paid, contact support.",
      "⌛ <b>Время оплаты истекло</b>\n\nЗаказ {order} отменён, так как оплата не поступила вовремя. Если вы уже оплатили — напишите в поддержку.", "⌛ <b>付款超时</b>\n\n订单 {order} 因未按时付款已取消。如已付款，请联系客服。", variables=("order",)),
    T("payment.provider_unavailable", "Payment", "⚠️ This payment method is temporarily unavailable. Please choose another one.", "⚠️ Способ оплаты временно недоступен. Выберите другой.", "⚠️ 该支付方式暂不可用，请选择其他方式。"),
    T("payment.cancel_confirm", "Payment", "Cancel order {order}?", "Отменить заказ {order}?", "确定取消订单 {order}？", variables=("order",)),
    T("payment.cancelled", "Payment", "Order {order} cancelled.", "Заказ {order} отменён.", "订单 {order} 已取消。", variables=("order",)),

    # ── Order statuses (customer-facing) ────────────────────────────────────
    T("status.order.pending", "Statuses", "🕓 Created", "🕓 Создан", "🕓 已创建"),
    T("status.order.awaiting_payment", "Statuses", "⏳ Awaiting payment", "⏳ Ожидает оплаты", "⏳ 待付款"),
    T("status.order.awaiting_confirmation", "Statuses", "🔎 Verifying payment", "🔎 Проверка оплаты", "🔎 付款核实中"),
    T("status.order.paid", "Statuses", "✅ Payment confirmed", "✅ Оплата подтверждена", "✅ 已确认付款"),
    T("status.order.processing", "Statuses", "⚙️ Processing", "⚙️ В обработке", "⚙️ 处理中"),
    T("status.order.completed", "Statuses", "🎉 Completed", "🎉 Выполнен", "🎉 已完成"),
    T("status.order.cancelled", "Statuses", "✕ Cancelled", "✕ Отменён", "✕ 已取消"),
    T("status.order.expired", "Statuses", "⌛ Expired", "⌛ Истёк", "⌛ 已过期"),
    T("status.order.failed", "Statuses", "⚠️ Failed", "⚠️ Ошибка", "⚠️ 失败"),
    T("status.order.refunded", "Statuses", "↩️ Refunded", "↩️ Возврат", "↩️ 已退款"),
    T("status.order.partially_refunded", "Statuses", "↩️ Partially refunded", "↩️ Частичный возврат", "↩️ 部分退款"),

    # ── Orders ──────────────────────────────────────────────────────────────
    T("orders.title", "Orders", "📦 <b>My orders</b>", "📦 <b>Мои заказы</b>", "📦 <b>我的订单</b>"),
    T("orders.empty", "Orders", "📦 <b>No orders yet</b>\n\nYour purchases will appear here.", "📦 <b>Заказов пока нет</b>\n\nЗдесь появятся ваши покупки.", "📦 <b>暂无订单</b>\n\n您的购买记录将显示在这里。"),
    T("orders.row", "Orders", "{status_icon} {number} · {total}", "{status_icon} {number} · {total}", "{status_icon} {number} · {total}", variables=("status_icon", "number", "total")),
    T("order.detail", "Orders",
      "📦 <b>Order {order}</b>\n\n{status}\n🗓 {date}\n\n{items}\n\n{summary}{payment}{delivery}",
      "📦 <b>Заказ {order}</b>\n\n{status}\n🗓 {date}\n\n{items}\n\n{summary}{payment}{delivery}",
      "📦 <b>订单 {order}</b>\n\n{status}\n🗓 {date}\n\n{items}\n\n{summary}{payment}{delivery}", variables=("order", "status", "date", "items", "summary", "payment", "delivery")),
    T("order.completed", "Orders",
      "🎉 <b>Thank you for your purchase!</b>\n\n<b>Order:</b> {order}\n<b>Product:</b> {product}{variant}\n<b>Quantity:</b> {qty}\n<b>Price:</b> {total}\n<b>Payment:</b> {method}\n<b>Date:</b> {date}\n\n<b>Your product:</b>\n{delivery}{instructions}{warranty}",
      "🎉 <b>Спасибо за покупку!</b>\n\n<b>Заказ:</b> {order}\n<b>Товар:</b> {product}{variant}\n<b>Количество:</b> {qty}\n<b>Сумма:</b> {total}\n<b>Оплата:</b> {method}\n<b>Дата:</b> {date}\n\n<b>Ваш товар:</b>\n{delivery}{instructions}{warranty}",
      "🎉 <b>感谢您的购买！</b>\n\n<b>订单：</b>{order}\n<b>商品：</b>{product}{variant}\n<b>数量：</b>{qty}\n<b>金额：</b>{total}\n<b>支付方式：</b>{method}\n<b>日期：</b>{date}\n\n<b>您的商品：</b>\n{delivery}{instructions}{warranty}",
      "Sent with automatically delivered goods", ("order", "product", "variant", "qty", "total", "method", "date", "delivery", "instructions", "warranty")),
    T("order.delivery_line", "Orders", "<code>{value}</code>", "<code>{value}</code>", "<code>{value}</code>", variables=("value",)),
    T("order.instructions", "Orders", "\n\n📘 <b>Instructions</b>\n{instructions}", "\n\n📘 <b>Инструкция</b>\n{instructions}", "\n\n📘 <b>使用说明</b>\n{instructions}", variables=("instructions",)),
    T("order.paid_manual_delivery", "Orders",
      "✅ <b>Payment confirmed · Order {order}</b>\n\nYour order is being prepared by our team. You'll receive it here shortly.",
      "✅ <b>Оплата подтверждена · Заказ {order}</b>\n\nНаша команда готовит ваш заказ. Вы получите его здесь в ближайшее время.",
      "✅ <b>付款已确认 · 订单 {order}</b>\n\n我们正在为您准备订单，稍后将在此发送。", variables=("order",)),
    T("order.delivery_failed", "Orders",
      "✅ <b>Payment confirmed · Order {order}</b>\n\nWe're finalising your delivery — a manager has been notified and will send your product shortly.",
      "✅ <b>Оплата подтверждена · Заказ {order}</b>\n\nЗавершаем выдачу — менеджер уже уведомлён и скоро отправит товар.",
      "✅ <b>付款已确认 · 订单 {order}</b>\n\n正在完成发货，客服已收到通知，将尽快为您发送商品。", variables=("order",)),
    T("order.refunded", "Orders", "↩️ <b>Refund · Order {order}</b>\n\n{amount} has been refunded{to_balance}.", "↩️ <b>Возврат · Заказ {order}</b>\n\n{amount} возвращено{to_balance}.", "↩️ <b>退款 · 订单 {order}</b>\n\n已退款 {amount}{to_balance}。", variables=("order", "amount", "to_balance")),
    T("order.refunded_to_balance", "Orders", " to your store balance", " на баланс магазина", "至您的商店余额"),
    T("order.cancelled_by_admin", "Orders", "Order {order} was cancelled by the store.", "Заказ {order} отменён магазином.", "订单 {order} 已被商店取消。", variables=("order",)),

    # ── Profile / balance / referrals ───────────────────────────────────────
    T("profile.text", "Profile",
      "👤 <b>Profile</b>\n\n<b>Name:</b> {name}\n<b>ID:</b> <code>{telegram_id}</code>\n<b>Customer since:</b> {joined}\n\n📦 Orders: <b>{orders}</b>\n💸 Spent: <b>{spent}</b>{balance}",
      "👤 <b>Профиль</b>\n\n<b>Имя:</b> {name}\n<b>ID:</b> <code>{telegram_id}</code>\n<b>С нами с:</b> {joined}\n\n📦 Заказов: <b>{orders}</b>\n💸 Потрачено: <b>{spent}</b>{balance}",
      "👤 <b>个人中心</b>\n\n<b>名称：</b>{name}\n<b>ID：</b><code>{telegram_id}</code>\n<b>注册时间：</b>{joined}\n\n📦 订单：<b>{orders}</b>\n💸 消费：<b>{spent}</b>{balance}",
      variables=("name", "telegram_id", "joined", "orders", "spent", "balance")),
    T("profile.balance", "Profile", "\n💰 Balance: <b>{balance}</b>", "\n💰 Баланс: <b>{balance}</b>", "\n💰 余额：<b>{balance}</b>", variables=("balance",)),
    T("referrals.text", "Referrals",
      "🎁 <b>Invite friends</b>\n\nShare your link and earn <b>{reward}</b> from every purchase your friends make{first_only}.\n\nYour link:\n<code>{link}</code>\n\n👥 Invited: <b>{invited}</b>\n🛍 Purchased: <b>{converted}</b>\n💰 Earned: <b>{earned}</b>",
      "🎁 <b>Приглашайте друзей</b>\n\nДелитесь ссылкой и получайте <b>{reward}</b> с каждой покупки друзей{first_only}.\n\nВаша ссылка:\n<code>{link}</code>\n\n👥 Приглашено: <b>{invited}</b>\n🛍 Купили: <b>{converted}</b>\n💰 Заработано: <b>{earned}</b>",
      "🎁 <b>邀请好友</b>\n\n分享您的链接，好友每次购买您都可获得 <b>{reward}</b>{first_only}。\n\n您的链接：\n<code>{link}</code>\n\n👥 已邀请：<b>{invited}</b>\n🛍 已购买：<b>{converted}</b>\n💰 已赚取：<b>{earned}</b>",
      variables=("reward", "first_only", "link", "invited", "converted", "earned")),
    T("referrals.first_only", "Referrals", " (first order only)", " (только с первого заказа)", "（仅限首单）"),
    T("referrals.share_text", "Referrals", "Check out {store_name} — premium digital products with instant delivery!", "Загляни в {store_name} — цифровые товары с мгновенной выдачей!", "来看看 {store_name} — 优质数字商品，即时发货！", variables=("store_name",)),
    T("referrals.reward_received", "Referrals", "🎁 You earned <b>{amount}</b> — your friend just made a purchase!", "🎁 Вы получили <b>{amount}</b> — ваш друг совершил покупку!", "🎁 您的好友完成了购买，您获得了 <b>{amount}</b>！", variables=("amount",)),

    # ── Language ────────────────────────────────────────────────────────────
    T("language.title", "Language", "🌐 <b>Choose your language</b>", "🌐 <b>Выберите язык</b>", "🌐 <b>选择语言</b>"),
    T("language.changed", "Language", "Language updated", "Язык изменён", "语言已更新"),

    # ── Support ─────────────────────────────────────────────────────────────
    T("support.text", "Support",
      "💬 <b>Support</b>\n\nWe're here to help — usually we reply within a few minutes.\n\nCreate a request and describe your question. Attach the order if it's about a purchase.",
      "💬 <b>Поддержка</b>\n\nМы на связи — обычно отвечаем в течение нескольких минут.\n\nСоздайте обращение и опишите вопрос. Если речь о покупке — укажите заказ.",
      "💬 <b>客服支持</b>\n\n我们随时为您服务，通常几分钟内回复。\n\n请新建工单并描述您的问题，如涉及订单请附上订单。"),
    T("support.ask_subject", "Support", "✉️ <b>New request</b>\n\nBriefly, what is it about? (one line)", "✉️ <b>Новое обращение</b>\n\nКратко — о чём вопрос? (одной строкой)", "✉️ <b>新建工单</b>\n\n请简要说明问题（一行）："),
    T("support.ask_message", "Support", "Now describe the issue in detail. You can attach a screenshot.", "Теперь опишите проблему подробнее. Можно приложить скриншот.", "请详细描述问题，可附上截图。"),
    T("support.created", "Support", "✅ <b>Request {ticket} created</b>\n\nWe'll reply right here in this chat.", "✅ <b>Обращение {ticket} создано</b>\n\nМы ответим прямо в этом чате.", "✅ <b>工单 {ticket} 已创建</b>\n\n我们将在此聊天中回复您。", variables=("ticket",)),
    T("support.tickets_title", "Support", "🗂 <b>My requests</b>", "🗂 <b>Мои обращения</b>", "🗂 <b>我的工单</b>"),
    T("support.tickets_empty", "Support", "You have no requests yet.", "У вас пока нет обращений.", "您还没有工单。"),
    T("support.ticket_view", "Support", "🎫 <b>{ticket} · {subject}</b>\n{status}\n\n{messages}", "🎫 <b>{ticket} · {subject}</b>\n{status}\n\n{messages}", "🎫 <b>{ticket} · {subject}</b>\n{status}\n\n{messages}", variables=("ticket", "subject", "status", "messages")),
    T("support.reply_prompt", "Support", "Send your message for request {ticket}:", "Отправьте сообщение по обращению {ticket}:", "请发送工单 {ticket} 的回复：", variables=("ticket",)),
    T("support.message_sent", "Support", "✓ Message sent", "✓ Сообщение отправлено", "✓ 消息已发送"),
    T("support.admin_reply", "Support", "💬 <b>Support · {ticket}</b>\n\n{message}", "💬 <b>Поддержка · {ticket}</b>\n\n{message}", "💬 <b>客服 · {ticket}</b>\n\n{message}", variables=("ticket", "message")),
    T("support.closed", "Support", "✓ Request {ticket} closed. Thank you!", "✓ Обращение {ticket} закрыто. Спасибо!", "✓ 工单 {ticket} 已关闭，谢谢！", variables=("ticket",)),
    T("status.ticket.open", "Statuses", "🟢 Open", "🟢 Открыто", "🟢 处理中"),
    T("status.ticket.waiting_customer", "Statuses", "💬 Awaiting your reply", "💬 Ждём вашего ответа", "💬 等待您的回复"),
    T("status.ticket.waiting_admin", "Statuses", "⏳ Awaiting support", "⏳ Ожидает ответа поддержки", "⏳ 等待客服回复"),
    T("status.ticket.resolved", "Statuses", "✅ Resolved", "✅ Решено", "✅ 已解决"),
    T("status.ticket.closed", "Statuses", "⚫ Closed", "⚫ Закрыто", "⚫ 已关闭"),

    # ── FAQ / pages ─────────────────────────────────────────────────────────
    T("faq.title", "FAQ", "❓ <b>Frequently asked questions</b>", "❓ <b>Частые вопросы</b>", "❓ <b>常见问题</b>"),
    T("faq.empty", "FAQ", "No questions yet.", "Вопросов пока нет.", "暂无常见问题。"),

    # ── Reviews ─────────────────────────────────────────────────────────────
    T("review.ask_rating", "Reviews", "⭐ <b>Rate {product}</b>\n\nHow was your experience?", "⭐ <b>Оцените {product}</b>\n\nКак вам покупка?", "⭐ <b>为 {product} 评分</b>\n\n您的体验如何？", variables=("product",)),
    T("review.ask_text", "Reviews", "Thanks! Add a short comment (or tap Skip).", "Спасибо! Добавьте короткий комментарий (или нажмите «Пропустить»).", "谢谢！请留下简短评价（或点击跳过）。"),
    T("review.skip", "Reviews", "Skip", "Пропустить", "跳过"),
    T("review.thanks", "Reviews", "💛 Thank you for your review!", "💛 Спасибо за отзыв!", "💛 感谢您的评价！"),

    # ── Customer notifications ──────────────────────────────────────────────
    T("notify.restock", "Notifications", "🔔 <b>{product}</b> is back in stock!", "🔔 <b>{product}</b> снова в наличии!", "🔔 <b>{product}</b> 已重新到货！", variables=("product",)),
    T("notify.balance_adjusted", "Notifications", "💰 Your balance was updated: <b>{amount}</b>\nCurrent balance: <b>{balance}</b>", "💰 Баланс изменён: <b>{amount}</b>\nТекущий баланс: <b>{balance}</b>", "💰 您的余额已更新：<b>{amount}</b>\n当前余额：<b>{balance}</b>", variables=("amount", "balance")),

    # ── Admin (Telegram) notifications ──────────────────────────────────────
    T("admin.new_order", "Admin notifications", "🆕 <b>New order {order}</b>\n{customer}\n{items}\nTotal: <b>{total}</b>", "🆕 <b>Новый заказ {order}</b>\n{customer}\n{items}\nСумма: <b>{total}</b>", "🆕 <b>新订单 {order}</b>\n{customer}\n{items}\n合计：<b>{total}</b>", variables=("order", "customer", "items", "total")),
    T("admin.payment_received", "Admin notifications", "💰 <b>Payment received · {order}</b>\n{customer}\n{total} via {method}", "💰 <b>Оплата получена · {order}</b>\n{customer}\n{total} через {method}", "💰 <b>已收款 · {order}</b>\n{customer}\n{total}，{method}", variables=("order", "customer", "total", "method")),
    T("admin.large_payment", "Admin notifications", "💎 <b>Large payment · {order}</b>\n{customer}\n<b>{total}</b> via {method}", "💎 <b>Крупный платёж · {order}</b>\n{customer}\n<b>{total}</b> через {method}", "💎 <b>大额付款 · {order}</b>\n{customer}\n<b>{total}</b>，{method}", variables=("order", "customer", "total", "method")),
    T("admin.payment_failed", "Admin notifications", "⚠️ <b>Payment problem · {order}</b>\n{reason}", "⚠️ <b>Проблема с оплатой · {order}</b>\n{reason}", "⚠️ <b>付款异常 · {order}</b>\n{reason}", variables=("order", "reason")),
    T("admin.refund", "Admin notifications", "↩️ <b>Refund · {order}</b>\n{amount} by {admin}", "↩️ <b>Возврат · {order}</b>\n{amount}, {admin}", "↩️ <b>退款 · {order}</b>\n{amount}，{admin}", variables=("order", "amount", "admin")),
    T("admin.low_stock", "Admin notifications", "🟠 <b>Low stock</b>\n{product}: {count} left", "🟠 <b>Мало товара</b>\n{product}: осталось {count}", "🟠 <b>库存不足</b>\n{product}：剩余 {count}", variables=("product", "count")),
    T("admin.out_of_stock", "Admin notifications", "🔴 <b>Out of stock</b>\n{product}", "🔴 <b>Товар закончился</b>\n{product}", "🔴 <b>已缺货</b>\n{product}", variables=("product",)),
    T("admin.new_customer", "Admin notifications", "👋 <b>New customer</b>\n{customer}", "👋 <b>Новый покупатель</b>\n{customer}", "👋 <b>新用户</b>\n{customer}", variables=("customer",)),
    T("admin.new_ticket", "Admin notifications", "🎫 <b>New ticket {ticket}</b>\n{customer}\n<b>{subject}</b>", "🎫 <b>Новое обращение {ticket}</b>\n{customer}\n<b>{subject}</b>", "🎫 <b>新工单 {ticket}</b>\n{customer}\n<b>{subject}</b>", variables=("ticket", "customer", "subject")),
    T("admin.ticket_message", "Admin notifications", "💬 <b>{ticket}</b> · {customer}\n{message}", "💬 <b>{ticket}</b> · {customer}\n{message}", "💬 <b>{ticket}</b> · {customer}\n{message}", variables=("ticket", "customer", "message")),
    T("admin.manual_delivery", "Admin notifications", "📮 <b>Manual delivery required · {order}</b>\n{items}", "📮 <b>Требуется ручная выдача · {order}</b>\n{items}", "📮 <b>需要人工发货 · {order}</b>\n{items}", variables=("order", "items")),
    T("admin.suspicious", "Admin notifications", "🚨 <b>Suspicious activity</b>\n{details}", "🚨 <b>Подозрительная активность</b>\n{details}", "🚨 <b>可疑活动</b>\n{details}", variables=("details",)),
    T("admin.error", "Admin notifications", "🧯 <b>Application error</b>\n{details}", "🧯 <b>Ошибка приложения</b>\n{details}", "🧯 <b>应用错误</b>\n{details}", variables=("details",)),
    T("admin.login_approval", "Admin notifications",
      "🔐 <b>Dashboard sign-in</b>\n\n{email}\nIP: <code>{ip}</code>\nDevice: {device}\n\nWas this you?",
      "🔐 <b>Вход в панель</b>\n\n{email}\nIP: <code>{ip}</code>\nУстройство: {device}\n\nЭто вы?",
      "🔐 <b>后台登录</b>\n\n{email}\nIP：<code>{ip}</code>\n设备：{device}\n\n是您本人吗？", variables=("email", "ip", "device")),
]

TEXTS_BY_KEY: dict[str, TextDef] = {t.key: t for t in TEXTS}

DEFAULT_LANGUAGES = [
    {"code": "en", "name": "English", "native_name": "English", "flag": "🇬🇧", "sort_order": 0},
    {"code": "ru", "name": "Russian", "native_name": "Русский", "flag": "🇷🇺", "sort_order": 1},
    {"code": "zh", "name": "Chinese", "native_name": "中文", "flag": "🇨🇳", "sort_order": 2},
]
